### ISSUE TITLE
SkyValidators Email and Url string empty check is allowing null

### ISSUE THREAD

**Issue by Blackbaud-MatthewMiles** [blackbaud/skyux-validation#16]
### Expected behavior
Entering a blank value into a form control with sky url or email validation should consider the formcontrol valid.

### Actual behavior
When entering a null string as a form control value, even though is is technically a blank value and 'valid', it throws an exception (since it is trying to check length of null). Some more rigorous checks need to be added to check null.

### Steps to reproduce
Make a form control that has a validator of either SkyValidators.email or SkyValidators.url and make the value null.

### Severity
Low, this is not publicly facing in the component docs yet and not used by many.  Also it is not typical to insert null into a formcontrol value by default.  I plan to add to the docs soon, so wanted to clean this up.

### Impact
Medium

**Comment by Blackbaud-MatthewMiles** [comment]
I am going to try to fix this.  Please assign to me.

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.2.1`
